# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MovieManager', '0001_initial'),
        ('AdminManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouritecritism',
            name='critism',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MovieManager.CriticCriticism', verbose_name=b''),
        ),
    ]
