# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminManager', '0007_news_relate_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritecritism',
            name='critism',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MovieManager.CriticCriticism', verbose_name='نقد'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='galleryNumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره گالری'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, choices=[('iran_cinema', 'سینمای ایران'), ('world_cinema', 'سینمای جهان'), ('honarmandan', 'هنر مندان'), ('TV', 'تلویزیون')], max_length=80, null=True, verbose_name='نوع خبر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='dateUpload',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان آپلود'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='admin/News/', verbose_name='عکس خبر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.TextField(blank=True, null=True, verbose_name='منبع'),
        ),
        migrations.AlterField(
            model_name='news',
            name='subText',
            field=models.TextField(blank=True, null=True, verbose_name='خلاصه خبر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='متن کامل خبر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='text',
            field=models.TextField(null=True, verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.TextField(null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='polloption',
            name='image',
            field=models.ImageField(upload_to='admin/PollImages/', verbose_name='عکس گزینه'),
        ),
        migrations.AlterField(
            model_name='polloption',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminManager.Poll', verbose_name='نظر سنجی'),
        ),
        migrations.AlterField(
            model_name='polloption',
            name='rate',
            field=models.IntegerField(null=True, verbose_name='رای'),
        ),
    ]
