# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminManager', '0009_auto_20160314_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='polloption',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='متن'),
        ),
    ]
