# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 17:40
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=b'celebrity/pictures', verbose_name=b'\xd8\xb9\xda\xa9\xd8\xb3')),
                ('name', models.CharField(blank=True, max_length=80, null=True, verbose_name=b'\xd9\x86\xd8\xa7\xd9\x85')),
                ('workingFields', models.TextField(blank=True, null=True, verbose_name=b'\xd8\xad\xd8\xb1\xd9\x81\xd9\x87')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name=b'\xd8\xaa\xd9\x88\xd8\xb6\xdb\x8c\xd8\xad')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name=b'\xd8\xaa\xd8\xa7\xd8\xb1\xdb\x8c\xd8\xae \xd8\xaa\xd9\x88\xd9\x84\xd8\xaf')),
                ('birthPlace', models.CharField(blank=True, max_length=80, null=True, verbose_name=b'\xd9\x85\xd8\xad\xd9\x84 \xd8\xaa\xd9\x88\xd9\x84\xd8\xaf')),
            ],
        ),
        migrations.CreateModel(
            name='Celebrity_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'Images/Celebrities', verbose_name=b'\xd8\xb9\xda\xa9\xd8\xb3')),
                ('celebrities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CelebrityManager.Celebrity', verbose_name=b'\xd8\xa8\xd8\xa7\xd8\xb2\xdb\x8c\xda\xaf\xd8\xb1\xd8\xa7\xd9\x86')),
            ],
        ),
    ]
