# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CelebrityManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celebrity_image',
            name='celebrities',
        ),
        migrations.AddField(
            model_name='celebrity_image',
            name='celebrities',
            field=models.ManyToManyField(to='CelebrityManager.Celebrity', verbose_name=b'\xd8\xa8\xd8\xa7\xd8\xb2\xdb\x8c\xda\xaf\xd8\xb1\xd8\xa7\xd9\x86'),
        ),
    ]
