# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CelebrityManager', '0002_auto_20160223_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celebrity_image',
            name='celebrities',
        ),
        migrations.DeleteModel(
            name='Celebrity_Image',
        ),
    ]
