# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CelebrityManager', '0004_auto_20160310_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_Celebrity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='celebrity/video_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='celebrity',
            name='description',
        ),
        migrations.AddField(
            model_name='celebrity',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='بیوگرافی'),
        ),
        migrations.AddField(
            model_name='video_celebrity',
            name='celebrity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CelebrityManager.Celebrity'),
        ),
    ]
