# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteCritism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, verbose_name=b'\xd8\xb9\xd9\x86\xd9\x88\xd8\xa7\xd9\x86')),
                ('subText', models.TextField(blank=True, null=True, verbose_name=b'\xd8\xae\xd9\x84\xd8\xa7\xd8\xb5\xd9\x87 \xd8\xae\xd8\xa8\xd8\xb1')),
                ('text', models.TextField(blank=True, null=True, verbose_name=b'\xd9\x85\xd8\xaa\xd9\x86 \xda\xa9\xd8\xa7\xd9\x85\xd9\x84 \xd8\xae\xd8\xa8\xd8\xb1')),
                ('source', models.TextField(blank=True, null=True, verbose_name=b'\xd9\x85\xd9\x86\xd8\xa8\xd8\xb9')),
                ('dateUpload', models.DateTimeField(blank=True, null=True, verbose_name=b'\xd8\xb2\xd9\x85\xd8\xa7\xd9\x86 \xd8\xa2\xd9\xbe\xd9\x84\xd9\x88\xd8\xaf')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'admin/News/', verbose_name=b'\xd8\xb9\xda\xa9\xd8\xb3 \xd8\xae\xd8\xa8\xd8\xb1')),
                ('name', models.CharField(blank=True, choices=[(b'iran_cinema', b'\xd8\xb3\xdb\x8c\xd9\x86\xd9\x85\xd8\xa7\xdb\x8c \xd8\xa7\xdb\x8c\xd8\xb1\xd8\xa7\xd9\x86'), (b'world_cinema', b'\xd8\xb3\xdb\x8c\xd9\x86\xd9\x85\xd8\xa7\xdb\x8c \xd8\xac\xd9\x87\xd8\xa7\xd9\x86'), (b'honarmandan', b'\xd9\x87\xd9\x86\xd8\xb1 \xd9\x85\xd9\x86\xd8\xaf\xd8\xa7\xd9\x86'), (b'TV', b'\xd8\xaa\xd9\x84\xd9\x88\xdb\x8c\xd8\xb2\xdb\x8c\xd9\x88\xd9\x86')], max_length=80, null=True, verbose_name=b'\xd9\x86\xd9\x88\xd8\xb9 \xd8\xae\xd8\xa8\xd8\xb1')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True, verbose_name=b'\xd8\xb9\xd9\x86\xd9\x88\xd8\xa7\xd9\x86')),
                ('text', models.TextField(null=True, verbose_name=b'\xd9\x85\xd8\xaa\xd9\x86')),
            ],
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'admin/PollImages/', verbose_name=b'\xd8\xb9\xda\xa9\xd8\xb3 \xda\xaf\xd8\xb2\xdb\x8c\xd9\x86\xd9\x87')),
                ('rate', models.IntegerField(null=True, verbose_name=b'\xd8\xb1\xd8\xa7\xdb\x8c')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminManager.Poll', verbose_name=b'\xd9\x86\xd8\xb8\xd8\xb1 \xd8\xb3\xd9\x86\xd8\xac\xdb\x8c')),
            ],
        ),
    ]
