# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminManager', '0002_favouritecritism_critism'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='name',
            new_name='category',
        ),
    ]
