# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminManager', '0003_auto_20160304_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'')),
            ],
        ),
        migrations.AlterField(
            model_name='favouritecritism',
            name='critism',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MovieManager.CriticCriticism', verbose_name=b'\xd9\x86\xd9\x82\xd8\xaf'),
        ),
    ]
