# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminManager', '0004_auto_20160304_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'\xd9\x86\xd8\xa7\xd9\x85')),
                ('galleryNumber', models.IntegerField(blank=True, null=True, verbose_name=b'\xd8\xb4\xd9\x85\xd8\xa7\xd8\xb1\xd9\x87 \xda\xaf\xd8\xa7\xd9\x84\xd8\xb1\xdb\x8c')),
            ],
        ),
        migrations.DeleteModel(
            name='Gallery1',
        ),
    ]
