# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminManager', '0006_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='relate_news',
            field=models.ManyToManyField(through='AdminManager.tag', to='AdminManager.News'),
        ),
    ]
