# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminManager', '0008_auto_20160310_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='عنوان'),
        ),
    ]
