# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminManager', '0013_remove_poll_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
