# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CelebrityManager', '0003_auto_20160224_0628'),
        ('MovieManager', '0002_auto_20160223_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Celebrity_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name=b'')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'MovieImages', verbose_name=b'\xd8\xb9\xda\xa9\xd8\xb3')),
                ('celebrities', models.ManyToManyField(related_name='images', to='CelebrityManager.Celebrity', verbose_name=b'')),
                ('movies', models.ManyToManyField(related_name='images', to='MovieManager.Movie', verbose_name=b'\xd9\x81\xdb\x8c\xd9\x84\xd9\x85 \xd9\x87\xd8\xa7')),
            ],
        ),
        migrations.RemoveField(
            model_name='movie_image',
            name='movies',
        ),
        migrations.DeleteModel(
            name='Movie_Image',
        ),
    ]
