# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieManager', '0004_movie_celebrity_image_galleryname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_celebrity_image',
            old_name='galleryName',
            new_name='galleryNumber',
        ),
        migrations.AddField(
            model_name='movie_celebrity_image',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name=b'\xd8\xaa\xd9\x88\xd8\xb6\xdb\x8c\xd8\xad'),
        ),
        migrations.AddField(
            model_name='movie_celebrity_image',
            name='in_homePage',
            field=models.BooleanField(default=False, verbose_name=b'\xd8\xaf\xd8\xb1 \xd8\xb5\xd9\x81\xd8\xad\xd9\x87 \xd8\xa7\xd8\xb5\xd9\x84\xdb\x8c \xd9\x86\xd8\xb4\xd8\xa7\xd9\x86 \xd8\xaf\xd8\xa7\xd8\xaf\xd9\x87 \xd8\xb4\xd9\x88\xd8\xaf'),
        ),
        migrations.AlterField(
            model_name='movie_celebrity_image',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name=b'\xd9\x86\xd8\xa7\xd9\x85'),
        ),
    ]
