# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieManager', '0009_auto_20160307_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='festival',
            field=models.IntegerField(blank=True, choices=[(0, b'\xd8\xac\xd8\xb4\xd9\x86\xd9\x88\xd8\xa7\xd8\xb1\xd9\x87 \xd9\x81\xd8\xac\xd8\xb1'), (1, b'\xd8\xac\xd8\xb4\xd9\x86 \xd8\xae\xd8\xa7\xd9\x86\xd9\x87 \xd8\xb3\xdb\x8c\xd9\x86\xd9\x85\xd8\xa7'), (2, b'\xd8\xac\xd8\xb4\xd9\x86 \xd9\x85\xd9\x86\xd8\xaa\xd9\x82\xd8\xaf\xd8\xa7\xd9\x86 \xd8\xb3\xdb\x8c\xd9\x86\xd9\x85\xd8\xa7')], null=True, verbose_name=b'\xd8\xac\xd8\xb4\xd9\x86\xd9\x88\xd8\xa7\xd8\xb1\xd9\x87'),
        ),
    ]
