# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 12:47
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieManager', '0010_auto_20160308_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='alias',
            field=models.CharField(max_length=100, verbose_name='نقش در فیلم'),
        ),
        migrations.AlterField(
            model_name='act',
            name='asli_ast',
            field=models.BooleanField(default=False, verbose_name='جز بازیگران اصلی است'),
        ),
        migrations.AlterField(
            model_name='act',
            name='celebrity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CelebrityManager.Celebrity', verbose_name='بازیگر'),
        ),
        migrations.AlterField(
            model_name='act',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieManager.Movie', verbose_name='فیلم'),
        ),
        migrations.AlterField(
            model_name='avamel',
            name='celebrity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='agent', to='CelebrityManager.Celebrity', verbose_name='بازیگر'),
        ),
        migrations.AlterField(
            model_name='avamel',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='agent', to='MovieManager.Movie', verbose_name='فیلم'),
        ),
        migrations.AlterField(
            model_name='avamel',
            name='role',
            field=models.CharField(blank=True, choices=[('kargardan', 'کارگردان'), ('nevisande', 'نویسنده'), ('tahiey_konande', 'تهیه کننده'), ('modir_tolid', 'مدیر تولید'), ('mojri_tarh', 'مدیر طرح'), ('Dastyar_aval_kargardan', 'دستیار اول کارگردان'), ('barname_riz', 'برنامه ریز'), ('modir_film_bardari', 'مدیر فیلم برداری'), ('tadvin', 'تدوین'), ('tarrah_sahne_va_lebas', 'طراح صحنه و لباس'), ('tarrah_chehre_pardazi', 'طراح چهره پردازی'), ('ahangsaz', 'آهنگساز'), ('seda_bardari', 'صدا بردار'), ('Seda_Gozari_va_mix', 'صدا گذار'), ('akkas', 'عکاس'), ('jelvehaye_vije_meydani', 'جلوه های ویژه'), ('jelvehaye_vije_basari', 'جلوه های بصری'), ('monshi_sahne', 'منشی صحنه'), ('moshaver_film_name', 'مشاور فیلم نامه'), ('moshaver_honari', 'مشاور هنری'), ('moshaver', 'مشاور')], max_length=40, null=True, verbose_name='کار اجرایی'),
        ),
        migrations.AlterField(
            model_name='award',
            name='candidate_type',
            field=models.IntegerField(blank=True, choices=[(0, 'برنده شده'), (1, 'نامزد شده'), (2, 'دیپلم افتخار')], null=True, verbose_name='برنده یا نامزد'),
        ),
        migrations.AlterField(
            model_name='award',
            name='category',
            field=models.TextField(blank=True, null=True, verbose_name='نوع جایزه'),
        ),
        migrations.AlterField(
            model_name='award',
            name='celebrity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CelebrityManager.Celebrity', verbose_name='بازیگر'),
        ),
        migrations.AlterField(
            model_name='award',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='award',
            name='festival',
            field=models.IntegerField(blank=True, choices=[(0, 'جشنواره فجر'), (1, 'جشن خانه سینما'), (2, 'جشن منتقدان سینما')], null=True, verbose_name='جشنواره'),
        ),
        migrations.AlterField(
            model_name='award',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieManager.Movie', verbose_name='فیلم'),
        ),
        migrations.AlterField(
            model_name='award',
            name='type',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='نوع بخش'),
        ),
        migrations.AlterField(
            model_name='criticcriticism',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='criticcriticism',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieManager.Movie', verbose_name='فیلم'),
        ),
        migrations.AlterField(
            model_name='criticcriticism',
            name='nameOfCritic',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='نام منتقد'),
        ),
        migrations.AlterField(
            model_name='criticcriticism',
            name='show_critic',
            field=models.BooleanField(default=False, verbose_name='نشان داده شود'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='خلاصه فیلم'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movie_actors', through='MovieManager.Act', to='CelebrityManager.Celebrity', verbose_name='بازیگران'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='avamel',
            field=models.ManyToManyField(related_name='movie_avamel', through='MovieManager.Avamel', to='CelebrityManager.Celebrity', verbose_name='عوامل'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='awards',
            field=models.ManyToManyField(through='MovieManager.Award', to='CelebrityManager.Celebrity', verbose_name='جوایز'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='dialogue',
            field=models.TextField(blank=True, null=True, verbose_name='دیالوگ'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='مدت زمان'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, to='MovieManager.Genre', verbose_name='ژانر'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='MovieManager.KeyWord', verbose_name='کلمات کلیدی'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='numUserRated',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد امتیاز دهندگان'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters', verbose_name='پوستر'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='posts',
            field=models.ManyToManyField(through='MovieManager.Post', to=settings.AUTH_USER_MODEL, verbose_name='پست ها'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.FloatField(blank=True, null=True, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='sale',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='فروش'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='سال تولید'),
        ),
        migrations.AlterField(
            model_name='movie_celebrity_image',
            name='celebrities',
            field=models.ManyToManyField(blank=True, null=True, related_name='images', to='CelebrityManager.Celebrity', verbose_name='بازیگر'),
        ),
        migrations.AlterField(
            model_name='movie_celebrity_image',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح'),
        ),
        migrations.AlterField(
            model_name='movie_celebrity_image',
            name='galleryNumber',
            field=models.IntegerField(choices=[(0, 'هیچ کدام'), (1, 'گالری ۱'), (2, 'گالری ۲'), (3, 'گالری ۳'), (4, 'گالری ۴')], default=0, verbose_name='گالری'),
        ),
        migrations.AlterField(
            model_name='movie_celebrity_image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='MovieImages', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='movie_celebrity_image',
            name='in_homePage',
            field=models.BooleanField(default=False, verbose_name='در صفحه اصلی نشان داده شود'),
        ),
        migrations.AlterField(
            model_name='movie_celebrity_image',
            name='movies',
            field=models.ManyToManyField(blank=True, null=True, related_name='images', to='MovieManager.Movie', verbose_name='فیلم ها'),
        ),
        migrations.AlterField(
            model_name='movie_celebrity_image',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieManager.Movie', verbose_name='پست'),
        ),
        migrations.AlterField(
            model_name='post',
            name='show_it',
            field=models.BooleanField(default=False, verbose_name='نشان داده شود'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='rateuserformovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieManager.Movie', verbose_name='فیلم'),
        ),
        migrations.AlterField(
            model_name='rateuserformovie',
            name='rate',
            field=models.IntegerField(verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='rateuserformovie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='statusofmovie',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='MovieManager.Movie', verbose_name='فیلم'),
        ),
        migrations.AlterField(
            model_name='statusofmovie',
            name='status',
            field=models.CharField(blank=True, choices=[('pish_tolid', 'پیش تولید'), ('film_bardari', 'فیلم برداری'), ('pas_tolid', 'پس تولید')], max_length=50, null=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='teaser',
            name='date_uploaded',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ اپلود'),
        ),
        migrations.AlterField(
            model_name='teaser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Teaser/Images', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='teaser',
            name='movie',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaser', to='MovieManager.Movie', verbose_name='فیلم'),
        ),
        migrations.AlterField(
            model_name='teaser',
            name='video_link',
            field=models.TextField(blank=True, null=True, verbose_name='لینک ویدیو'),
        ),
        migrations.AlterField(
            model_name='typeofmovie',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='MovieManager.Movie', verbose_name='فیلم'),
        ),
        migrations.AlterField(
            model_name='typeofmovie',
            name='type',
            field=models.TextField(blank=True, null=True, verbose_name='نوع فیلم'),
        ),
        migrations.AlterField(
            model_name='usercriticism',
            name='content',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='usercriticism',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieManager.Movie', verbose_name='فیلم'),
        ),
        migrations.AlterField(
            model_name='usercriticism',
            name='show_it',
            field=models.BooleanField(default=False, verbose_name='نشان داده بشود'),
        ),
        migrations.AlterField(
            model_name='usercriticism',
            name='userPro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserManager.UserIMDB', verbose_name='کاربر'),
        ),
    ]
