# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieManager', '0011_auto_20160310_1247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CriticCriticism',
            new_name='Reviewer_Review',
        ),
        migrations.RenameModel(
            old_name='UserCriticism',
            new_name='User_Review',
        ),
        migrations.AlterField(
            model_name='movie_celebrity_image',
            name='celebrities',
            field=models.ManyToManyField(blank=True, related_name='images', to='CelebrityManager.Celebrity', verbose_name='بازیگر'),
        ),
        migrations.AlterField(
            model_name='movie_celebrity_image',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='images', to='MovieManager.Movie', verbose_name='فیلم ها'),
        ),
    ]
