# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieManager', '0013_auto_20160310_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Summary',
            new_name='summary',
        ),
    ]
