# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieManager', '0018_auto_20160318_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='movie',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='MovieManager.Movie', verbose_name='فیلم'),
        ),
    ]
