# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieManager', '0020_auto_20160412_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام'),
        ),
    ]
