# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 19:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0003_auto_20160306_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimdb',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name=b'\xd9\x86\xd8\xa7\xd9\x85'),
        ),
        migrations.AlterField(
            model_name='userimdb',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userIMDB', to=settings.AUTH_USER_MODEL, verbose_name=b'\xdb\x8c\xd9\x88\xd8\xb2\xd8\xb1'),
        ),
    ]
