# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 12:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0004_auto_20160308_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimdb',
            name='aboutMe',
            field=models.TextField(blank=True, null=True, verbose_name='درباره من'),
        ),
        migrations.AlterField(
            model_name='userimdb',
            name='birthday',
            field=models.DateField(null=True, verbose_name='تولد'),
        ),
        migrations.AlterField(
            model_name='userimdb',
            name='expireTimeToAccountPro',
            field=models.DateField(null=True, verbose_name='زمان باقی مانده تا اتمام اعتبار'),
        ),
        migrations.AlterField(
            model_name='userimdb',
            name='favouriteActor',
            field=models.ManyToManyField(related_name='user_like_as_actor', to='CelebrityManager.Celebrity', verbose_name='بازیگران مورد علاقه'),
        ),
        migrations.AlterField(
            model_name='userimdb',
            name='favouriteDirector',
            field=models.ManyToManyField(related_name='user_like_as_director', to='CelebrityManager.Celebrity', verbose_name='کارگردانان مورد علاقه'),
        ),
        migrations.AlterField(
            model_name='userimdb',
            name='favouriteGenre',
            field=models.ManyToManyField(to='MovieManager.Genre', verbose_name='ژانر های مورد علاقه'),
        ),
        migrations.AlterField(
            model_name='userimdb',
            name='favouriteMovie',
            field=models.ManyToManyField(related_name='in_favourite_movie', to='MovieManager.Movie', verbose_name='فیلم های مورد علاقه'),
        ),
        migrations.AlterField(
            model_name='userimdb',
            name='hasProAccount',
            field=models.BooleanField(default=False, verbose_name='کاربر ویژه'),
        ),
        migrations.AlterField(
            model_name='userimdb',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='userimdb',
            name='picture',
            field=models.ImageField(null=True, upload_to='user/pictures', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='userimdb',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='حرفه'),
        ),
        migrations.AlterField(
            model_name='userimdb',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userIMDB', to=settings.AUTH_USER_MODEL, verbose_name='یوزر'),
        ),
        migrations.AlterField(
            model_name='userimdb',
            name='viewed_movie',
            field=models.ManyToManyField(related_name='in_viewed_movie', to='MovieManager.Movie', verbose_name='فیلم ها دیده شده'),
        ),
    ]
