# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieManager', '0014_auto_20160310_1848'),
        ('UserManager', '0006_auto_20160313_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='movie',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='movie',
            field=models.ManyToManyField(blank=True, related_name='in_Watchlist', to='MovieManager.Movie', verbose_name='فیلم ها'),
        ),
    ]
