# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 11:28
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserManager', '0007_auto_20160313_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userimdb',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='userimdb',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='userimdb',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userimdb',
            name='user',
        ),
        migrations.AddField(
            model_name='userimdb',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
