# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CelebrityManager', '0005_auto_20160316_1235'),
        ('MovieManager', '0024_movie_is_top_profit'),
        ('UserManager', '0009_auto_20160420_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListCelebrity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, verbose_name='عنوان')),
                ('celebrity', models.ManyToManyField(blank=True, related_name='in_list_user', to='CelebrityManager.Celebrity', verbose_name='هنرمندان')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='celebrityList', to='UserManager.UserIMDB', verbose_name='کاربران')),
            ],
        ),
        migrations.CreateModel(
            name='ListMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, verbose_name='عنوان')),
                ('movie', models.ManyToManyField(blank=True, related_name='in_list_user', to='MovieManager.Movie', verbose_name='فیلم ها')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='movieList', to='UserManager.UserIMDB', verbose_name='کاربران')),
            ],
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
