# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0010_auto_20160621_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='listcelebrity',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ'),
        ),
        migrations.AddField(
            model_name='listmovie',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ'),
        ),
    ]
