# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieManager', '0006_auto_20160306_1622'),
        ('CelebrityManager', '0003_auto_20160224_0628'),
        ('UserManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostForCelebrity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Posted_on', to='CelebrityManager.Celebrity')),
            ],
        ),
        migrations.AddField(
            model_name='userimdb',
            name='viewed_movie',
            field=models.ManyToManyField(blank=True, null=True, related_name='in_viewed_movie', to='MovieManager.Movie', verbose_name=b'\xd9\x81\xdb\x8c\xd9\x84\xd9\x85 \xd9\x87\xd8\xa7 \xd8\xaf\xdb\x8c\xd8\xaf\xd9\x87 \xd8\xb4\xd8\xaf\xd9\x87'),
        ),
        migrations.AddField(
            model_name='postforcelebrity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Posted_on_Celebrity', to='UserManager.UserIMDB'),
        ),
    ]
