# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0002_auto_20160306_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimdb',
            name='viewed_movie',
            field=models.ManyToManyField(related_name='in_viewed_movie', to='MovieManager.Movie', verbose_name=b'\xd9\x81\xdb\x8c\xd9\x84\xd9\x85 \xd9\x87\xd8\xa7 \xd8\xaf\xdb\x8c\xd8\xaf\xd9\x87 \xd8\xb4\xd8\xaf\xd9\x87'),
        ),
    ]
