# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 21:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserManager', '0008_auto_20160418_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userimdb',
            options={},
        ),
        migrations.AlterModelManagers(
            name='userimdb',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='userimdb',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='userimdb',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userimdb',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
