# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieManager', '0003_auto_20160224_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_celebrity_image',
            name='galleryName',
            field=models.IntegerField(choices=[(0, b'\xd9\x87\xdb\x8c\xda\x86\xdb\x8c'), (1, b'\xda\xaf\xd8\xa7\xd9\x84\xd8\xb1\xdb\x8c \xdb\xb1'), (2, b'\xda\xaf\xd8\xa7\xd9\x84\xd8\xb1\xdb\x8c \xdb\xb2'), (3, b'\xda\xaf\xd8\xa7\xd9\x84\xd8\xb1\xdb\x8c \xdb\xb3'), (4, b'\xda\xaf\xd8\xa7\xd9\x84\xd8\xb1\xdb\x8c \xdb\xb4')], default=0, verbose_name=b'\xda\xaf\xd8\xa7\xd9\x84\xd8\xb1\xdb\x8c'),
        ),
    ]
