# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieManager', '0008_auto_20160306_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='candidate_type',
            field=models.IntegerField(blank=True, choices=[(0, b'\xd8\xa8\xd8\xb1\xd9\x86\xd8\xaf\xd9\x87 \xd8\xb4\xd8\xaf\xd9\x87'), (1, b'\xd9\x86\xd8\xa7\xd9\x85\xd8\xb2\xd8\xaf \xd8\xb4\xd8\xaf\xd9\x87'), (2, b'\xd8\xaf\xdb\x8c\xd9\xbe\xd9\x84\xd9\x85 \xd8\xa7\xd9\x81\xd8\xaa\xd8\xae\xd8\xa7\xd8\xb1')], null=True, verbose_name=b'\xd8\xa8\xd8\xb1\xd9\x86\xd8\xaf\xd9\x87 \xdb\x8c\xd8\xa7 \xd9\x86\xd8\xa7\xd9\x85\xd8\xb2\xd8\xaf'),
        ),
    ]
