# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieManager', '0012_auto_20160310_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewer_review',
            old_name='show_critic',
            new_name='show_it',
        ),
        migrations.AddField(
            model_name='user_review',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avamel',
            name='role',
            field=models.CharField(blank=True, choices=[('kargardan', 'کارگردان'), ('nevisande', 'نویسنده'), ('tahiey_konande', 'تهیه کننده'), ('modir_tolid', 'مدیر تولید'), ('mojri_tarh', 'مدیر طرح'), ('dastyar_aval_kargardan', 'دستیار اول کارگردان'), ('barname_riz', 'برنامه ریز'), ('modir_film_bardari', 'مدیر فیلم برداری'), ('tadvin', 'تدوین'), ('tarrah_sahne_va_lebas', 'طراح صحنه و لباس'), ('tarrah_chehre_pardazi', 'طراح چهره پردازی'), ('ahangsaz', 'آهنگساز'), ('seda_bardari', 'صدا بردار'), ('seda_Gozari_va_mix', 'صدا گذار'), ('akkas', 'عکاس'), ('jelvehaye_vije_meydani', 'جلوه های ویژه'), ('jelvehaye_vije_basari', 'جلوه های بصری'), ('monshi_sahne', 'منشی صحنه'), ('moshaver_film_name', 'مشاور فیلم نامه'), ('moshaver_honari', 'مشاور هنری'), ('moshaver', 'مشاور')], max_length=40, null=True, verbose_name='کار اجرایی'),
        ),
    ]
