# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieManager', '0014_auto_20160310_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusofmovie',
            name='status',
            field=models.CharField(blank=True, choices=[('پیش تولید', 'پیش تولید'), ('فیلم برداری', 'فیلم برداری'), ('پس تولید', 'پس تولید')], max_length=50, null=True, verbose_name='وضعیت'),
        ),
    ]
