# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieManager', '0015_auto_20160317_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusofmovie',
            name='is_red',
            field=models.BooleanField(default=False, verbose_name='قرمز است'),
            preserve_default=False,
        ),
    ]
