# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieManager', '0017_auto_20160317_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='dialogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن')),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='dialogue',
        ),
        migrations.AddField(
            model_name='dialogue',
            name='movie',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='MovieManager.Movie', verbose_name='فیلم'),
        ),
    ]
