# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieManager', '0019_auto_20160318_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusofmovie',
            name='is_red',
        ),
        migrations.AddField(
            model_name='statusofmovie',
            name='color',
            field=models.CharField(blank=True, choices=[('blue', 'آبی'), ('red', 'قرمز'), ('black', 'مشکی')], max_length=20, null=True, verbose_name='رنگ'),
        ),
    ]
